name: Deploy to Vercel

on:
  push:
    branches:
      - master # Cambia a la rama que desees

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Cambia a la versión de Node.js que necesites

      - name: Install dependencies
        run: npm install # O yarn install, según el gestor de paquetes que uses

      - name: Build project
        run: npm run build # Cambia el comando según tu proyecto (React, Next.js, etc.)

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} # Despliegue en producción
