name: Deploy to Vercel

on:
  push:
    branches:
      - master # Cambia a la rama que desees

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Cambiar de directorio a 'frontend' y ejecutar npm install
      - name: Install dependencies
        run: |
          cd front-end
          npm install

      # Cambiar de directorio a 'frontend' y ejecutar build
      - name: Build project
        run: |
          cd front-end
          npm run build

      # Cambiar de directorio a 'frontend' y desplegar a Vercel
      - name: Deploy to Vercel
        run: |
          cd front-end
          npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
